name: pantagonthings
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  circle_nav_bar: ^1.0.0
  http: ^0.13.4
  giffy_dialog: ^2.1.0
  loading_animation_widget: ^1.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_dialogs: ^2.1.1
  animated_bottom_navigation_bar: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true
